sudo: false
language: node_js
node_js:
- '8'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
- npm run coveralls
deploy:
  provider: npm
  email: m@ttjohnston.com
  api_key:
    secure: lSxThf3n2cgEAmlcfRjvtz9L2P/WOHtoHbUluSW+hdOszfthweETSCl5Yy01DaMCnpKsQnp207pio4hEnqRkWaw6hlEZ0RNdlcIbQFKojy+Z2zy4dmEOvRMo5jwunB/VoOw5sUkM8OJs+KAGjubIvy/b15mMKhZGIfrSZZDBjrBPSXToBgT6h1PsR9LP69vX8M1Pwxc0PXOOryd77JxmQMtzHgI8XKIfyCvBZv3vZl7BqGSyiesAoTvzPDVqQiOiC7P37JtINPmHhChqk4kAXBXJuD3phC1XTw+7c2RcyzsCdMNfrfssEzljTjcv5A88DGGVz0B21wUt56rHii4YqLrjzauvs2nIfEeACEXDdbBHha/hPDngOt2/g5SCdINeBqG7aV4b/lO2A9sanG2kSM0iWnxAsMwhBOtL8V0zGugk2KGAdRwJfxqSRoKYTBUf03B+f+JzahfiiaZrGO4+PyWHq48YAYHWlaU+knGlFau+qOjCdaW4bT8OYY5Huy9ETTkXgBXUMfw/4UogjtaIL3k8hwIKLxDqb0ZTXzCC3CNPSekjkfP8JYdOOkjzLSrLrvKAcz6TH0/wo9xtqRinThQgXwdvFpSg/4AUa8dT7q5rdfOoRE1d7z9hO7Lyu7cAKMfnbu+4nnSilugyKgNNiCd/I9xYx0PNwrxv/NqSDcU=
  on:
    repo: johnstonmatt/current-type-of
